### ISSUE TITLE
Allow saving GHC to a custom location

### ISSUE THREAD

**Issue by lortabac** [Franciman/vabal#2]
It would very useful to be able to change the location where GHC is saved. There are situations in which we have limited choice on the directories we are allowed to use, and this option may be a deal breaker in those cases.

**Comment by Franciman** [comment]
Currently GHC downloading is managed by [ghcup](https://github.com/haskell/ghcup) , so this issue is `ghcup` related.
Generally speaking, I think that the task of downloading and managing various GHC versions for a given operating system is best solved by an external tool, they look useful on their own, and also, *probably* ghcup can become official?
Maybe we could add different backends (for retrieving GHC) that vabal could use (and possibly implement our own)?

For now a thing you could do is edit the ghcup script, but watchout, if you update ghcup, you'll receive a fresh copy of ghcup with default options again.
Watch here for more infos: https://github.com/haskell/ghcup/issues/7

**Comment by hasufell** [comment]
> It would very useful to be able to change the location where GHC is saved. There are situations in which we have limited choice on the directories we are allowed to use, and this option may be a deal breaker in those cases.

Can you give more information why your home directory is not writable?

**Comment by lortabac** [comment]
The idea behind this proposal is to let `vabal`/`ghcup` work in more settings and environments. That's why I did not mention any particular use case.

One particular environment that comes to my mind is Gitlab CI, which only allows caching files that are in the project directory (or in a subdirectory at any depth). For this use case, making the parent directory of `.ghcup` configurable would be enough.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup/commit/75e48da9a04ea1d4bfe7174b4b559297aa19ad62

**Comment by lortabac** [comment]
@hasufell Great! Thank you.
